version: '3.8'

services:
  bot-for-koshka:
    build: .
    container_name: bot-for-koshka
    env_file: .env        # Ensure you have a .env file with your bot's token
    restart: unless-stopped  # Ensures the container restarts if it crashes or the system reboots
    volumes:
      - .:/usr/src/app     # Mounts the current directory into the container, for live updates
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

